export const ActionTypes = {
  UPDATE_LOADING: "UPDATE_LOADING",
  GET_ITEMS: "GET_ITEMS",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILURE: "GET_ITEMS_FAILURE",
  ITEMS_FILTER_CHANGE: "ITEMS_FILTER_CHANGE",
  CLEAR_ITEMS_LIST: "CLEAR_ITEMS_LIST",
  RESET_STORE: "RESET_STORE",
  SAVE_USER: "SAVE_USER",
  USER_LOGOUT: "USER_LOGOUT"
};

export const SourceType = {
  NEWSAPI_SEARCH: "NEWSAPI_SEARCH",
  NEWSAPI_HEADLINES: "NEWSAPI_HEADLINES",
  RECOMMENDATIONS: "RECOMMENDATIONS",
}

// export default ActionTypes;
